baseURL = 'https://blog.0x29a.me/'
languageCode = 'en-us'
title = '0x29a.me'
theme = ["github.com/adityatelange/hugo-PaperMod"]
sectionPagesMenu = 'main'
enableEmoji = true

[outputs]
	home = ["html", "rss", "json"]

[params]
	showBreadCrumbs = true
	defaultTheme = 'dark'
	disableThemeToggle = true
	author = 'christian frantzen'
	[params.editPost]
		URL = 'https://github.com/Cephra/blog/edit/main/content'
		Text = 'edit'
		appendFilePath = true
	[params.assets]
		favicon	= 'favicon.ico'
	[params.profileMode]
		enabled = true
		title = "Christian Frantzen"
		subtitle = "a software developer"
		[[params.profileMode.buttons]]
			name = 'about'
			url = '/about'
		[[params.profileMode.buttons]]
			name = 'posts'
			url = '/posts'
	[[params.socialIcons]]
		name = "github"
		url = "https://github.com/Cephra"
	[[params.socialIcons]]
		name = "email"
		url = "mailto:cf@0x29a.me"
	[[params.socialIcons]]
		name = "rss"
		url = "/index.xml"