services:
  app:
    user: 1000:1000
    build:
      context: .
    volumes:
      - ./:/app
      - ../../:/app/mnt-workspace
      - /opt/venv
      - /home/szt/.vscode-oss:/home/szt/.vscode-oss
    network_mode: host
    command: python test.py
