name: Checks that hugo can successfully build

on:
    push:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v4
            -   
                name: Setup hugo
                uses: peaceiris/actions-hugo@v3
                with:
                    hugo-version: '0.145.0'
            -
                name: Run a hugo build
                run: hugo --minify